<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SqlPerformanceLab.Core\SqlPerformanceLab.Core.csproj" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
</Project>
